# Travis-CI Build for koreader-base
# see travis-ci.org for details

dist: trusty
sudo: required
# sudo: false

cache:
  apt: true
  directories:
      - $HOME/.ccache

env:
    - EMULATE_READER=1 CC=gcc
    - EMULATE_READER=1 CC=clang
    - TARGET=kindle
    - TARGET=kobo
    - TARGET=android NDKREV=r9c
    - TARGET=android NDKREV=r11c
    - TARGET=android NDKREV=r12b

addons:
  apt:
    packages:
      - g++-4.8
      - libsdl1.2-dev
      - luarocks
      # for luasec
      - libssl1.0.0
      - nasm
      # OpenSSL likes this (package contains makedepend)
      - xutils-dev

before_install: source .ci/before_install.sh

install:
    - if [ "$EMULATE_READER" = 1 ]; then source .ci/emulator_install.sh; fi
    - if [ "$TARGET" = kindle ]; then .ci/kindle_install.sh; fi
    - if [ "$TARGET" = kobo ]; then .ci/kobo_install.sh; fi
    - if [ "$TARGET" = android ]; then source .ci/android_install.sh; fi

script:
    - .ci/build_script.sh
    - if [ "$EMULATE_READER" = 1 ]; then source .ci/test_script.sh; fi
