# Travis-CI Build for koreader-base
# see travis-ci.org for details

language: c

compiler:
    - gcc

env:
    - EMULATE_READER=1 USE_NO_CCACHE=1

install:
    - sudo apt-get install libsdl1.2-dev luarocks
    - sudo luarocks install busted

script:
    - make fetchthirdparty
    - make
    - sudo cp luajit-2.0/src/luajit /usr/bin/luajit
    - make test
