name: Build Release

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:

  release:

    name: Release

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: false
          sparse-checkout: .ci
          show-progress: false

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: artifacts/new
          skip-decompress: true

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./.ci/build.release.sh

# vim: foldmethod=marker foldlevel=0
