name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:

  Lint:
    runs-on: ubuntu-latest
    container:
      image: koreader/kobase:0.3.4-20.04
      options: --user root
    env:
      BASH_ENV: '/root/.bashrc'
      CLICOLOR_FORCE: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 1
          show-progress: false
      - name: Fix checkout ownership
        run: chown 'root:root' .
      - name: Checkout base
        run: git submodule update --init --depth 1 base
      - name: Lint
        run: .ci/check.sh

  Emulator:
    needs: Lint
    uses: ./.github/workflows/build_matrix.yml
    with:
      matrix: |
        {
          "include": [
            {
              "job": "GCC",
              "cache": "emu_gcc",
              "image": "koreader/kobase:0.3.4-20.04",
              "test": true
            }
          ]
        }

  macOS:
    needs: Emulator
    uses: ./.github/workflows/build_matrix.yml
    with:
      fail-fast: false
      matrix: |
        {
          "include": [
            {
              "job": "13 x86-64 🔨15.2 🎯10.15",
              "cache": "macos.13_x86_64_xcode.15.2_10.15",
              "runs-on": "macos-13",
              "target": "macos",
              "xcode_version": "15.2",
              "macosx_deployment_target": "10.15",
              "artifact": "KOReader-*.7z",
              "test": true
            },
            {
              "job": "14 ARM64 🔨15.4 🎯11.0",
              "cache": "macos.14_ARM64_xcode.15.4_11.0",
              "runs-on": "macos-14",
              "target": "macos",
              "xcode_version": "15.4",
              "macosx_deployment_target": "11.0",
              "artifact": "KOReader-*.7z",
              "test": true
            }
          ]
        }

# vim: foldmethod=marker foldlevel=0
