name: Build

on:
  workflow_call:
    inputs: &INPUTS
      jobs:
        description: 'Run the specified list of job ids'
        default: 'default'
        required: false
        type: string
      publish:
        description: 'Publish a release to GitHub'
        default: false
        required: false
        type: boolean
  workflow_dispatch:
    inputs: *INPUTS

defaults:
  run:
    shell: bash

jobs:

  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          clean: false
          fetch-depth: 1
          show-progress: false
          sparse-checkout: |
            .ci
            .github/workflows
      - name: Generate outputs
        id: generate
        run: |
          set -o noglob
          >>"${GITHUB_OUTPUT}" ./.ci/build.prepare.sh ${{ inputs.jobs }}
    outputs:
      lint: ${{ steps.generate.outputs.lint }}
      emulator: ${{ steps.generate.outputs.emulator }}
      macos: ${{ steps.generate.outputs.macos }}
      platform: ${{ steps.generate.outputs.platform }}

  lint:
    name: Lint
    needs: prepare
    if: needs.prepare.outputs.lint
    uses: ./.github/workflows/build.lint.yml

  emulator:
    name: Emulator
    needs: [prepare, lint]
    if: |
      !cancelled() &&
      needs.prepare.outputs.emulator &&
      contains('skipped success', needs.lint.result)
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ needs.prepare.outputs.emulator }}
      fail_fast: true

  macos:
    name: macOS
    needs: [prepare, lint, emulator]
    if: |
      !cancelled() &&
      needs.prepare.outputs.macos &&
      contains('skipped success', needs.lint.result) &&
      contains('skipped success', needs.emulator.result)
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ needs.prepare.outputs.macos }}

  platform:
    name: Platform
    needs: [prepare, lint, emulator]
    if: |
      !cancelled() &&
      needs.prepare.outputs.platform &&
      contains('skipped success', needs.lint.result) &&
      contains('skipped success', needs.emulator.result)
    uses: ./.github/workflows/build.matrix.yml
    with:
      jobs: ${{ needs.prepare.outputs.platform }}

  release:
    name: Release
    needs: [emulator, macos, platform]
    if: |
      inputs.publish && !cancelled() &&
      contains('skipped success', needs.lint.result) &&
      contains('skipped success', needs.emulator.result) &&
      contains('skipped success', needs.macos.result) &&
      contains('skipped success', needs.platform.result)
    # permissions:
    #   contents: ${{ inputs.publish && 'write' || 'read' }}
    uses: ./.github/workflows/build.release.yml

# vim: foldmethod=marker foldlevel=0
