name: Push / PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
