name: Push / PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    ignore_tags: '*'
  pull_request:

jobs:

  lint:
    name: Lint
    uses: ./.github/workflows/_lint.yml

  build:
    name: Build
    needs: lint
    uses: ./.github/workflows/_build.yml
